#! /bin/sh

"$HOME/.config/.screenlayout/screen-layout.sh" &

pgrep -x sxhkd >/dev/null || sxhkd &

picom &

"$HOME/.config/polybar/launch.sh" &

# Static Powermenu with rofi
#. /home/ozymandias/.config/polybar/pwidgets/scripts/powermenu.sh &

bspc monitor -d I II III IV V VI VII VIII IX X

# Cursor
xsetroot -cursor_name left_ptr &

# Windows Settings
bspc config border_width 2
bspc config window_gap 12
bspc config top_padding 8
bspc config bottom_padding 8
bspc config left_padding 8
bspc config right_padding 8
bspc config single_monocle false
bspc config gapless_monocle false
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_modifier mod4
bspc config split_ratio 0.50

# Windows Border Settings
bspc config focused_border_color "#3888A0"
bspc config normal_border_color "#D4D4D4"
bspc config active_border_color "#073642"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
